[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00aaff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#222222"
textColor = "#ffffff"
